### ISSUE TITLE
Use with Canvas

### ISSUE THREAD

**Issue by antonytrupe** [HarryStevens/d3-geo-scale-bar#25]
Doesn't look like its working, but I may be missing something trivial.

const scaleBar = d3.geoScaleBar()
    .projection(projection)
    .size([400, 320]);
d3.select(canvas).call(scaleBar);

**Comment by HarryStevens** [comment]
Not currently, but it would be a great feature.

**Comment by antonytrupe** [comment]
I'm not sure where to start. Any pointers?

**Comment by HarryStevens** [comment]
I'd assumed that d3-axis had support for Canvas, and I was going to suggest looking at how it was done there. But it turns out it does not, and Mike himself decided against trying to implement it: https://github.com/d3/d3-axis/issues/2

My suggestion would be to layer an SVG element on top of your Canvas element and append the scale bar to the SVG.

**Comment by HarryStevens** [comment]
I'm gonna go ahead and close this now.
